### ISSUE TITLE
Need an elegant (DRY) way to log function times

### ISSUE THREAD

**Issue by MareoRaft** [ProveMath/prove-math#10]
Original message from Greg to Matt:
-----------------------------------------------------

Hey Matt,

A few weeks ago we talked a little about how to log function calls and see what takes the most time to run.  You may have already thought of this, but I was looking over decorators and realized they can provide a pretty nice solution.

The idea is we make a function (or class, you can use classes as decorators too) that looks something like this:

    def log_function_call(func):
       def new_func():
           start_time = time.time()
           func()
           elapsed_time = time.time() - start_time
           send_info_to_log_file(date_and_time, func.__name__, elapsed_time, any_other_info_we_want_logged)
       return new_func

Then in the graph_extend, digraph_extend and dag files we just need to add the line
@log_function_call
above each function definition in those files.  E.g.

    @log_function_call
    def ancestors:
       ...
    
    @log_function_call
    def descendants:
       ...

etc.  This article gives an example of using decorators to execute code just before and after a function call: http://www.artima.com/weblogs/viewpost.jsp?thread=240808

Best,
Greg

**Comment by MareoRaft** [comment]
@gmattson92 : I can't think of any caveats to this approach.  It sounds like the perfect solution.  I'm giving you the green light to implement it.

Make sure that `new_func` takes in the arguments that `func` would and passes them along to `func`.  Similarly, make sure whatever `func` returns gets returned by `new_func`.  I'm guessing this will work:

    def log_function_call(func):
        def new_func(**args):
            start_time = time.time()
            out = func(**args)
            elapsed_time = time.time() - start_time
            send_info_to_log_file(date_and_time, func.name, elapsed_time, any_other_info_we_want_logged)
            return out
    return new_func

I have not read your article yet.  Look up the (single and double star)[http://stackoverflow.com/questions/36901/what-does-double-star-and-star-do-for-python-parameters] thingies in Python.

**Comment by gmattson92** [comment]
I'll check it out and make sure there is a good way to pass the arguments in and be able to have `new_func` actually return the output of `func`.  After finishing the dag `make_user_suggestion` stuff of course.

**Comment by MareoRaft** [comment]
So to make your life a little easier, here is a brief explanation of the star thingies...

`*`
--------
Given a list `L`, then the expression `*L` unpacks the list into it's elements separated by commas (aka arguments).

So if `L = [1, 2, 3]`, then `f(L)` is the same as `f([1, 2, 3])`, but `f(*L)` is the same as `f(1, 2, 3)`.

The star has ANOTHER function, and that is to pack a function's input arguments into a list (like the same thing as before, but in reverse).

```
    def g(*li):
        for item in li:
            print(item)
```

Here you will see that `g("hello", "there")` prints "hello" and then prints "there".  So the arguments "hello" and "there" were packed into a list, so that `li` equaled `["hello", "there"].

`**`
---------
The DOUBLE star is analogous to the single star, but instead of lists is deals with DICTIONARIES, and instead of arguments it deals with KEYWORD ARGUMENTS...

Given a dictionary `D`, then the expression `*D` unpacks the dictionary into it's key=value items separated by commas (aka keyword arguments).

So if `D = {"a": "A", "b": "B"}`, then `f(D)` is the same as `f({"a": "A", "b": "B"})`, but `f(*D)` is the same as `f(a="A", b="B")`.

The double-star has ANOTHER function, and that is to pack a function's input keyword arguments into a dictionary (like the same thing as before, but in reverse).

```
    def g(**di):
        for key, value in di.items():
            print(str(key) + ": " + str(value))
```

Here you will see that `g(color="blue", height=45)` prints "color: blue" and then prints "height: 45" .  So the keyword arguments color="blue" and height=45 were packed into a dictionary, so that `di` equaled `{color: "blue", height: 45}`.

**Comment by gmattson92** [comment]
@MareoRaft So it turns out your guess version
```
def log_function_call(func):
    def new_func(*args, **kwargs):
        start_time = time.time()
        out = func(*args, **kwargs)
        elapsed_time = time.time() - start_time
        send_info_to_log_file(date_and_time, func.name, elapsed_time, any_other_info_we_want_logged)
        return out
    return new_func
```
works like a charm.  I get the idea behind the single and double stars too.  Thanks for the explanation.

I've added the elapsed_time decorator to log.py.  We will probably need to iron out some specifics of how it should send things to the log file, and maybe which file to send to (keep a dedicated file for time logging separate from the general-purpose one?)

**Comment by MareoRaft** [comment]
We are keeping a dedicated & separate file, like you suggested, called elapsed_times.log.

The only issue now is that I'm getting all these elapsed time messages printed to the terminal when I run code/tests.  That's a separate issue though, and should be an easy fix.
