### ISSUE TITLE
reverse dictionary in short_sighted_depth_to_successors_dict

### ISSUE THREAD

**Issue by MareoRaft** [ProveMath/prove-math#11]
@gmattson92 : (by the way, i know you are busy with grad school decisions, etc, so don't feel any time pressure on these issues.)

Looking at the code for the `short_sighted_depth_to_successors_dict` method, there are a few suggestions I have:

  1. I think the first variable should be named "successor_to_depth", for clarity (In addition, I think the method name should also be "descendant" (singular).)
  2. The whole algorithm where you take a dictionary and reverse it should be removed from the function.  Create a function in **helper.py** that takes in an arbitrary dictionary and returns its inverse. (Actually, I'll create that function now for you.  I will call it `invert_dict`)
  3. What would be EVEN BETTER (from an optimization / elegance perspective) is if we had built the `descendant_to_distance` method to be a `distance_to_descendants` method in the first place.  This would not be difficult.  However, I will ask you to refrain from doing this, as our time is better spent elsewhere.

**Comment by MareoRaft** [comment]
My function `invert_dict` will not return an OrderedDict.  What is the easiest way to convert a dict to an OrderedDict?

**Comment by MareoRaft** [comment]
Note to self: write test functions for flatten_list_of_lists, append_value_to_key, and inverted_dict.

**Comment by gmattson92** [comment]
@MareoRaft I don't know if it is the best way, but you can convert a dict to an OrderedDict like this:
```
def convert_dict_to_ordered(unordered_dict):
    ordered_dict = OrderedDict()
    for k in sorted(unordered_dict.keys(), reverse=True):
        ordered_dict[k] = unordered_dict[k]
    return ordered_dict

d = {3: 'non', 2: 'alphabetical', 1: 'values'}
#d.keys() will return a list with 1, 2, 3 in some arbitrary order. Usually [1, 2, 3] but this is not guaranteed
ordered_d = convert_dict_to_ordered(d)
#ordered_d.keys() will return [3, 2, 1] unambiguously
#likewise ordered_d.values() will return ['non', 'alphabetical', 'values']
```
And obviously we can insert whatever sorting details we want into the `sorted(unordered_dict.keys())` call to get the desired ordering.

Bear in mind OrderedDict.keys() does not return a list, but an iterable that might need to be typecast to a list.  Same with values() and items().

**Comment by MareoRaft** [comment]
I finished `invert_dict`, which I decided to call `reverse_dict` instead, and added it to the repo.  You can git commit your current state (even if it's not working yet) and git pull to get it.

I will finish up `convert_dict_to_ordered` too soon, so that you can keep your focus on the high-level `suggest_node` stuff.  I'll keep what you said in mind.

**Comment by MareoRaft** [comment]
Upon finding some recipes, there isn't even a need for a `convert` ordered dict function.  Use:

```
# regular unsorted dictionary
d = {'banana': 3, 'apple':4, 'pear': 1, 'orange': 2}

# dictionary sorted by key (USE THIS ONE)
OrderedDict(sorted(d.items(), key=lambda t: t[0]))


# dictionary sorted by value
OrderedDict(sorted(d.items(), key=lambda t: t[1]))


# dictionary sorted by length of the key string
OrderedDict(sorted(d.items(), key=lambda t: len(t[0])))
```

**Comment by gmattson92** [comment]
Oooh that's much more elegant than looping over the keys and adding them to the OrderedDict one by one.  Nicely done.

**Comment by MareoRaft** [comment]
Tests passing.  Closing issue.
