### ISSUE TITLE
In Greg's Firefox, words bigger than circles on right sidebar

### ISSUE THREAD

**Issue by MareoRaft** [ProveMath/prove-math#15]
For example, the logout circle reads "ogou".

This MIGHT already be fixed, since this issue is based on a slightly older version, but I think it has everything to do with the LINUX version of Firefox.

**Comment by MareoRaft** [comment]
@gmattson92 Could you quickly try the following things to rule them out?

1. Use Ctrl + 0 to reset font size
2. Go to Edit, Preferences, General, and then click on Fonts & Colors.  Make sure you have a normal setting.  (Like Helvetica, Arial, Times New Roman and Tahoma, and a normal font size).

**Comment by gmattson92** [comment]
1. Resetting the font size did not work.
2. Changing the font did work.  Looks like it's just a quirk of the specific open source fonts my Linux defaults to.  Also I only needed to change the font, not the size.  Scaling up or down works correctly with other fonts.
