### ISSUE TITLE
Unable to see nodes that have dependencies.

### ISSUE THREAD

**Issue by mmuddasani** [ProveMath/prove-math#2]
I loaded "category-theory.pre-json" into the database and ran the server locally. I tried to learn the first node. I expected dependent nodes to show on the page with the node graph, but nothing visibly changed.

I noticed some an error from the server on my terminal screen. I do not know whether or not it is related to the root cause. Here was the server output:

main.py:165: SyntaxWarning: name 'our_DAG' is used prior to global declaration
  global our_DAG
main.py:166: SyntaxWarning: name 'all_nodes' is used prior to global declaration
  global all_nodes # this is a list of dictionaries
Node array loaded with length: 3
Edge array loaded with length: 3
got message: {"command":"open","identifier":{"account_type":"local"}}
got message: {"command":"learn-node","node_id":"equatable","mode":"learn","identifier":{"account_type":"local"}}
ERROR:tornado.application:Uncaught exception in /websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tornado/websocket.py", line 417, in _run_callback
    callback(*args, **kwargs)
  File "main.py", line 135, in on_message
    user.learn_node(ball['node_id'])
  File "/Users/Mohith/prog/prove-math/server/lib/user.py", line 54, in learn_node
    self.USERS.update(self._identifier_dict(), {'$addToSet': {'learned_node_ids': node_id}}, False)
  File "/Users/Mohith/prog/prove-math/server/lib/user.py", line 35, in _identifier_dict
    'account.type': self.account_type,
AttributeError: 'User' object has no attribute 'account_type'
A websocket has been closed.

**Comment by MareoRaft** [comment]
We do not yet support people who are NOT logged in.  Please created a LinkedIn account if you don't have one, and login using that (facebook, google, and github work on provemath.org but will not work locally).  If this doesn't work, let me know and I'll re-open the issue.

**Comment by mmuddasani** [comment]
I have used my LinkedIn account to try and login, but it is not working.

What follows is the server output of my attempts, in case it helps in discovering the issue:

main.py:178: SyntaxWarning: name 'our_DAG' is used prior to global declaration
  global our_DAG
main.py:179: SyntaxWarning: name 'all_nodes' is used prior to global declaration
  global all_nodes # this is a list of dictionaries
main.py:192: SyntaxWarning: name 'our_mongo' is used prior to global declaration
  global our_mongo
Node array loaded with length: 5
Edge array loaded with length: 7
got message: {"command":"open","identifier":{"account_type":"local"}}
A websocket has been closed.
got params!!!!
Login failed
'NoneType' object has no attribute 'text'
got message: {"command":"open","identifier":{"account_type":"local"}}
A websocket has been closed.
got params!!!!
Login failed
'NoneType' object has no attribute 'text'
got message: {"command":"open","identifier":{"account_type":"local"}}
got params!!!!
Login failed
'NoneType' object has no attribute 'text'
A websocket has been closed.
got message: {"command":"open","identifier":{"account_type":"local"}}
got params!!!!
Login failed
'NoneType' object has no attribute 'text'
got params!!!!
Login failed
'NoneType' object has no attribute 'text'
A websocket has been closed.
got message: {"command":"open","identifier":{"account_type":"local"}}

**Comment by MareoRaft** [comment]
Check out the "try" block around main.py line 83.  See which error in particular is tripping the try block.  That error is the problem.  The "try-except" block was created to fail for a different scenario (one where somebody tries to use incorrect or expired login credentials).

I'm guessing the error is the request_root thing on line 83, but I can't verify since I'm not the one getting the error :)

Once you get more info, @theodoresiu might be able to give you further insight.

**Comment by MareoRaft** [comment]
We now support users who are not logged in.  Closing this.  Re-open if you have problems.
