### ISSUE TITLE
need mongo search index

### ISSUE THREAD

**Issue by gmattson92** [ProveMath/prove-math#21]
@theodoresiu It looks like Matt and I cannot use the search functionality on our local copies of the server because we need to add a text index to mongo.

No rush at all since we don't actually need it for anything now, but when you have some time can you post a step-by-step for how you did this?  Or just directing us to whatever resource you used to figure it out ought to suffice too.  Thanks!

**Comment by MareoRaft** [comment]
@gmattson92 Theo helped me today with the search index.

See `http://localhost/docs/mongo.html` for instructions.
