### ISSUE TITLE
hanging_dominion and successors are virtually the same

### ISSUE THREAD

**Issue by MareoRaft** [ProveMath/prove-math#7]
@gmattson92 

The only difference between the hanging_dominion method and the successors method is that hanging_dominion is capable of taking MULTIPLE nodes as input, but successors is only capable of taking a single node as input.

In a perfect would, we could re-implement successors to be able to take in both single and multiple node inputs, and then do away with hanging_dominion entirely.

Let's see if we can monkey patch the function tomorrow.

**Comment by MareoRaft** [comment]
@gmattson92 

Can you add this to your list of things to finish by next week?  So you should delete `hanging_dominion` method and replace any uses of `hanging_dominion` in the code with `successors`.

**Comment by gmattson92** [comment]
@MareoRaft  Done and done.
