### ISSUE TITLE
successor (singular) is inefficient

### ISSUE THREAD

**Issue by MareoRaft** [ProveMath/prove-math#9]
@gmattson92 When I originally created successor, I got ALL of the successors, and then returned the first one:

```
def successor(self, node): # should follow the same exact pattern as predecessor
		ss = list(self.successors_iter(node))
		if ss:
			return ss[0]
		else:
			return None
```

Ideally, we would just grab one in the first place.  As you can see, when we typecast `self.successors_iter(node)` to a `list()`, it gets ALL the successors.

Instead of typecasting to a list, you should use the iterable to get the next successor.  Make sure you have a way to check if there are no successors at all.

(remember to do the same for predecessor once I approve your code for successor)

:)

**Comment by MareoRaft** [comment]
Not to steal your thunder, but here are two possible solution ideas you could try...

```
# code here that creates an iterator 'my_iter'
try:
    first = my_iter.next()
except StopIteration:
    # Code here for the case where the iterator is empty
```

where my_iter is our successors_iter(node).  Or you could try...

```
for successor in successors_iter(node):
    return successor
return None
```

which is my personal favorite :)

But the important thing is that YOU UNDERSTAND what this means and why it works.  Otherwise you won't get anything out of this.  There is a super great [article](http://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) that explains what iterators (generators) are and how you can make your own iterators.

**Comment by gmattson92** [comment]
Ooh great catch!  How did you even notice this?  I completely missed it.

**Comment by MareoRaft** [comment]
Well I knew when I first wrote `successor` that it was kindof a makeshift solution.  I saw it just now when I was browsing over your `successors`-related code.  It's fortunate that your used `successors_iter` in the code for this function, because when I originally wrote the code, I wasn't aware that `successors` actually used an iterable behind the scenes.  The iterable is the perfect tool for grabbing only 1 successor.

**Comment by gmattson92** [comment]
Fixed!

There's also a neat trick for checking that an iterator is not empty.  `next(iterable, [default])` allows for an optional second argument to use as the return value if you have already reached the end of `iterable`, instead of raising `StopIteration`.  So in this case we can avoid using the try/except block to look for that error.
